package trans

// Code generated by Test_GeneateFunc in trans_test.go. DO NOT EDIT.

// ACC0000 :
/* 
 尊敬的{{.Name}}，您好！
 */
var ACC0000 = func() Trans { return GetTransMap("ACC0000") }
// ACC0001 :
/* 
 您正在激活账户，请点击下面链接完成激活
 */
var ACC0001 = func() Trans { return GetTransMap("ACC0001") }
// ACC0002 :
/* 
 (若链接无效，请将地址复制到浏览器地址栏并打开)
 */
var ACC0002 = func() Trans { return GetTransMap("ACC0002") }
